language: ruby
dist: trusty
sudo: required
cache: bundler
services:
  - mongodb
bundler_args: --without yard guard benchmarks tools
after_success:
  - '[ "$TRAVIS_RUBY_VERSION" = "2.3.1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
script: "bundle exec rake ci"
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0
  - rbx-3
  - jruby
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
