language: ruby
dist: trusty
sudo: required
cache: bundler
services:
  - mongodb
bundler_args: --without yard guard benchmarks tools
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
script: "bundle exec rake ci"
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - rbx-3
  - jruby
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
matrix:
  allow_failures:
    - rvm: rbx-3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
