language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks tools
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - CODECLIMATE_REPO_TOKEN=886f3b795e74159719804f8e18b853f4c23a81bd814404e52ec248a0dae6d656
script: "bundle exec rake ci"
rvm:
  - 2.0
  - 2.1
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
services:
  - mongodb
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
